config/routes.rb
Rails.application.routes.draw do
  get 'comment/new'

  get 'post/new'
  get 'session/show'

   post 'post/create'
   delete 'post/destroy' => 'post#destroy'
   post 'comment/create'

  post "user/show"
  post "user/edit"
  post "user/login"
  get "session/login"
  post "session/login"
  get "session/logout"
   root 'session#login'

    resources :user 
    resources :post do
      resources :comment 
    end
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
end

app/models/follo.rb
class Follo < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :title, :description,  :presence => true
	default_scope {order('created_at DESC')}

	belongs_to :user
	has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base

	validates :name, :email, :password,  :presence => true
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
	validates :password ,:length => {:within => 8..10}
	validates :email, :uniqueness=>true

	has_many :posts
	has_many :comments

end
						 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # before_action :log_in?,  :except => :new
  # around_filter :set_time_zone

  def log_in?
	 if session[:id]
    @current_user= User.find(session[:id])
		true
	 else
		#flash[:notice] => "Login_require"
		redirect_to(:controller => 'session', :action => 'login')
    end
  end
  
  def log_out?
   # debugger
    if session[:id]
      false
      redirect_to(:controller => 'session', :action => 'login')
    end 
   end 



  # def set_time_zone
  #   if log_in?
  #     Time.use_zone(@current_user.time_zone) { yield }
  #   else
  #     yield
  #   end
  # end
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
	before_action :log_in?

  def new
  	#debugger
  	@comment= Comment.new
  end
 
  def create
 
  	@comment= @current_user.comments.new(comment_params)
  	#@comment.post_id = params[:comment][:post]
  	@comment.save
  	redirect_to :user_index
  end

  # def index
  # 	@user= User.find(params[:id])
  # 	@post= Post.find(params[:user_id])
  # 	@comment= Comment.find(params[:post_id])
  	
  # end

  def edit
  	@comment=Comment.find(params[:id])
  end

  def update
 	
  	@comment=Comment.find(params[:id])
		if @current_user.id == @comment.user_id 
			@comment.update_attributes(comment_params)
    end
			redirect_to :user_index
	end		

  	
  	

	def destroy
		
		@comment=Comment.find(params[:id])
		if @current_user.id == @comment.user_id
			@comment.destroy
		else
		# :notice =>"Only User can delete"	
	end
		redirect_to :user_index
	end  	
			
		

	  	
	private
	def comment_params
		params.require(:comment).permit(:user_id,:post_id,:description)
	end  		

end
	  			

app/controllers/post_controller.rb
class PostController < ApplicationController
  before_action :log_in?

  def index
    @posts = @current_user.posts.all
  end
    
  
  def new
  	@post = Post.new
  end

  def create
  	@post = @current_user.posts.new(post_params)
  	#debugger
  	@post.save
  	redirect_to :user_index
  end
 
  def edit
    @post= Post.find(params[:id]) 
  end   

  def update
    @post= Post.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to :post_index,     :notice => "Post Updated"
    else
      render "edit"
    end
  end
    
    

  def destroy
  	@post= Post.find(params[:id])
		@post.destroy
		redirect_to :post_index, :notice => "User Deleted"
  	
  end

  private
    def post_params
    	params.require(:post).permit(:title, :description)
    end


end

app/controllers/session_controller.rb
class SessionController < ApplicationController


def new
	session[:id]= @user.id
end

# def islogin
# 	if session[:id]
# 	   # @current_user = 	session[:id]
# 		render "login"
# 	else (session[:id]== nil)
# 		render "index"
# 	end	
# end

  def login
 		@user= User.where(:email => params[:email], :password => params[:password]).first
 		# @user = user.first
 		#debugger
 		unless @user.blank?
 			SessionController.new
 			session[:id]= @user.id
 			redirect_to(:controller=>"user" , :action=>"index")
 		else
 			render "login"
    end
  end

  def logout
  	 #debugger
  	session[:id]= nil
    @current_user= nil
  	render "login"
  	
  end

  def show
    @users= User.all
    
  end

# def destroy
# 	if session[:id]==nil
# 	session[:id].destroy

# 	end
#
end
		

app/controllers/user_controller.rb
class UserController < ApplicationController
	before_action :log_in?,  :except => [:login , :new, :create]
	# after_action :log_out?, :except => [:login , :new, :create]
	include UserHelper


	def index
		
		@posts = @current_user.posts
		@comments = @current_user.comments
		@users = User.all
		@posts= Post.all
		# @user= User.find(params[:id])
					# session[:id]= nil #session destroy

	end

	# def login
	# 	@user= User.where(:name => params[:name], :password => params[:password]).first
	# 	# @user = user.first
	# 	#debugger
	# 	unless @user.blank?
	# 		SessionController.new
	# 		session[:id]= @user.id
	# 		render "index"
	# 	else
	# 		render "login"
	#   end
	# end
	
	def show
		#debugger
		@user= User.find(params[:id])
    @post= @user.posts
    #@comment= Comment.find(params[:post_id])
	end
	
	# def log_out
	# end

	def new
		@user = User.new
		# @users = User.all
	end

	def create
		
		@user= User.new(user_params)
		#paaswod genrt
		# @user.password = 
		if @user.save
			redirect_to :user_index,   :notice => "User Created & Saved"
		else 	
			render "new"
		end
	end

	def edit
		@user= User.find(params[:id])
	end

	def update
			@user= User.find(params[:id])
		if @user.update_attributes(user_params)
			render "index",      :notice => "User Updated"
		else
			render "edit"
		end	
	end

	def destroy
		@user= User.find(params[:id])
		@user.destroy
		redirect_to :new_user , :notice => "User Deleted"
	end

	private
		def user_params
				params.require(:user).permit(:name,:password,:email, :contact, :college)
		end
end

	


	
	

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper

end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_helper.rb
module UserHelper
	def find_user id
		User.find(id) rescue 'anonymous'
	end

end

app/views/comment/edit.html.erb
 <!DOCTYPE html>
<html>
	<head>
		<title></title>
		<link rel="stylesheet" type="text/css" href="application.css">
	</head>
	<body>
	<div id="wrapper">
		<div id="header">
			<h1 class="T"><center><b>Edit Comment</b></center></h1>
		</div><br><br>
		<div id="lo"><%= link_to "Home",user_index_path ,{style:"color: #4169E1"}%></div>
			<div id="left_navigation"><br><br>
				<%= form_for @comment, url:{action:"update"} do|f|%>
					<div class="new"style="Color:white"><b>
					<%= f.label  :comment  %>
					<%= f.hidden_field :post_id, :value => params[:post_id] %>
					<div><%= f.text_area :description, cols: "65", rows: "7"%></div></b><br><br>
					</div>
					<%= f.submit "Update", {style: "color: #4169E1"}%>
				<%end%>
			</div>
			</div>
	</body>
</html>
						
					
					
				

			
 
				

app/views/comment/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" type="text/css" href="application.css">
</head>
<body>

	<div id="wrapper">
		<div id="header">
			<h1 class="T"><center><b><%= @user.name %></b></center></h1>
			
		</div><br><br>
		<div id="lo"><%= link_to "Logout",session_logout_path ,{style:"color: #4169E1"}%></div>
		<div id="you">	<%= link_to "Post", new_post_path, {style: "color: #4169E1"}%></div>
		<div id="my">	<%= link_to "My Post", post_index_path, {style: "color: #4169E1"}%></div>
		<div id="users"><%= link_to "All Users", session_show_path,{style: "color: #4169E1"} %>
	  </div>

		

			  <%unless @posts.blank? %>
	  <hr>
			<% @posts.each do|post| %>
				<div class="P">Title<br></div>
				<%= post.title %><br>
				<div class="P">Description <br></div>
				<%= post.description %><br>
				<ul type="square">
						<% @comment = post.comments %>
						<div class="P">Comments<br></div>
						<% @comment.each do|com|%>
						<li><%= com.description%></li>
				<hr>
			<%end%>
		<%end%>
				
			


</div>
</body>
</html>

app/views/comment/new.html.erb
 <!DOCTYPE html>
<html>
	<head>
		<title></title>
		<link rel="stylesheet" type="text/css" href="application.css">
	</head>
	<body>
	<div id="wrapper">
		<div id="header">
			<h1 class="T"><center><b>Comment</b></center></h1>
		</div><br><br>
		<div id="lo"><%= link_to "Home",user_index_path ,{style:"color: #4169E1"}%></div>
			<div id="left_navigation"><br><br>
				<%= form_for @comment, url:{action:"create"} do|f|%>
					<div class="new"style="Color:white"><b>
					<%= f.label  :comment  %>
					<%= f.hidden_field :post_id, :value => params[:post] %>
					<div><%= f.text_area :description, cols: "65", rows: "7"%></div></b><br><br>
					</div>
					<%= f.submit "Create", {style: "color: #4169E1"}%>
				<%end%>
			</div>
			</div>
	</body>
</html>
						
					
					
				

			
 
				

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirstApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<% flash.each do|key, value| %>
	<p><%=value%></p>
<%end%>
<%= yield %>

</body>
</html>

app/views/post/edit.html.erb
<!DOCTYPE html>
<html>	
	<head>
		<title>New Post</title>
		<link rel="stylesheet" type="text/css" href="application.css">
	</head>
	<body>
	<div id="wrapper">
		<div id="header">
			<h1 class="T"><center><b>Edit Post</b></center></h1>
		</div><br><br>
		<div id="lo"><%= link_to "Home",user_index_path ,{style:"color: #4169E1"}%></div>
		<div id="left_navigation"><br><br>
			<%= form_for @post  do|f|%>
				<%if @post.errors.any? %>
					<h1>Error</h1>
					<ul>
					<%= @post.errors.full_messages%>
					</ul>
				<%end%>
				<div class="new"style="Color:white"><b>
					<%= f.label  :title  %>
					<p><%= f.text_field :title, :size=> 30 %></p><br><br></b>
				</div>
				<div class= "new"style="color:white"><b>
					<%= f.label  :description %> 
					<p><%= f.text_area :description, cols: "65", rows: "7" %></p></b>
					<%= f.submit "Update" ,{style: "color: #4169E1"}%>
				</div>
			<%end%>
		</div>
		</div>
	</body>
</html>

app/views/post/index.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title></title>
		<link rel="stylesheet" type="text/css" href="application.css">
	</head>
	<body>
	<div id="wrapper">
		<div id="header">
			<div class="T"><b>Posts By <%= @current_user.name%></b></div>
		</div><br><br>
		
		<div id="lo"><%= link_to "Home",user_index_path ,{style:"color: #4169E1"}%></div>
		<div id="you">	<%= link_to "Post", new_post_path, {style: "color: #4169E1"}%></div>
	  <%unless @posts.blank? %>
	  <hr>
			<% @posts.each do|post| %>
				<div class="P">Title<br></div>
				<%= post.title %><br>
				<div class="P">Description <br></div>
				<%= post.description %><br>
				<%=link_to"Delete", post, :method => :delete  %>|
				<%= link_to "Edit", edit_post_path(post)%>
				<hr>
			<%end%>
		<%end%>
		</div>
	</body>
</html>	  	
		

app/views/post/new.html.erb
 <!DOCTYPE html>
<html>	
	<head>
		<title>New Post</title>
		<link rel="stylesheet" type="text/css" href="application.css">
	</head>
	<body>
	<div id="wrapper">
		<div id="header">
			<h1 class="T"><center><b>New Post</b></center></h1>
		</div><br><br>
		<div id="lo"><%= link_to "Home",user_index_path ,{style:"color: #4169E1"}%></div>
		<div id="left_navigation"><br><br>
			<%= form_for @post, url:{action:"create"} do|f|%>
				<%if @post.errors.any? %>
					<h1>Error</h1>
					<ul>
					<%= @post.errors.full_messages%>
					</ul>
				<%end%>
				<div class="new"style="Color:white"><b>
					<%= f.label  :title  %>
					<p><%= f.text_field :title, :size=> 30 %></p><br><br></b>
				</div>
				<div class= "new"style="color:white"><b>
					<%= f.label  :description %> 
					<p><%= f.text_area :description, cols: "65", rows: "7" %></p></b>
					<%= f.submit "Create" ,{style: "color: #4169E1"}%>
				</div>
			<%end%>
		</div>
		</div>
	</body>
</html>

<!-- remote: true -->
					
	
					

app/views/session/login.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title></title>
		<link rel="stylesheet" type="text/css" href="application.css">
	</head>
	<body>
	<div id="wrapper">
		<div id="tech" ><b>The Techno Freakers..</b></div>
		<div id="h" ><b>View With Few</b></div>
		<div id="login"><br><br>
			<%= form_tag(:action => 'login')do|f|%>
			<div class="P" style="color:white"><b>
				Email
				<div><%= text_field_tag :email %></div></b><br><br>
			</div>
			<div class="P" style="color:white"><b>
				Password
			<div><%= password_field_tag :password %></div></b><br><br>
			</div>
			<%= submit_tag ('Login'),{style: "color: #4169E1"} %> | <%= link_to "Sign Up" ,new_user_path, {style: "color: #4169E1"}%>
			<%end%>
		</div>
		</div>
	</body>
</html>
		
			
			
		
	
			

	

	
	
	
	
	
	


				
		

				
		

app/views/session/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" type="text/css" href="application.css">
</head>


<body>

	<div id="wrapper">
	<div id="header">
		<h1 class="T"><center><b>All User</b></center></h1>
	</div><br><br>
		<div id="lo"><%= link_to "Logout",session_logout_path ,{style:"color: #4169E1"}%></div>
		<div id="you">	<%= link_to "Post", new_post_path, {style: "color: #4169E1"}%></div>
		<div id="my">	<%= link_to "My Post", post_index_path, {style: "color: #4169E1"}%></div>
		<div id="home"><%= link_to "Home",user_index_path ,{style:"color: #4169E1"}%></div>

			<ul type="Square">
		
					<% @users.each do|user| %>
						<li><%= link_to user.name ,user_path(user),{style:"color: #4169E1"}%><br></li>
						<hr>
					<% end %>
				</ul>
</div>
</body>
</html>





				
				    

app/views/user/edit.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title></title>
		<link rel="stylesheet" type="text/css" href="application.css">
	</head>
		<body bgcolor="Burlywood">
			<div id="header">
				<h1><center>Edit User</center></h1>
			</div>
				<%= form_for @user do|f|%>
						<% if @user.errors.any? %>
								<h1>Error</h1>
								<ul>
									<%= @user.errors.full_messages%>
								</ul>
						<%end%>
						<p style="Color:brown"><b>
							<%= f.label :name %>
							<p><%= f.text_field :name %> </p><br><br></b>
						</p>
							<p style="Color:brown"><b>
					   	<%= f.label :password%>
							<p><%= f.password_field :password %></p><br><br>
							</b>
						</p>
						<p style="color: brown"><b>
							<%= f.label :email %>
							<p><%= f.text_field :email %> </p><br><br></b>
						</p>
						<p style="Color:brown"><b>
							<%= f.label :contact %>
							<p><%= f.text_field :contact %></p><br><br></b>
						</p>
						<p style="Color:brown"><b>
							<%= f.label :college %>
							<p><%= f.text_field :college %></p><br><br></b>
						</p>
					
						<%= f.submit "Update User" %>
				<%end%>
		</body>
</html>





	

app/views/user/index.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title></title>
		<link rel="stylesheet" type="text/css" href="application.css">
	</head>
	<body>
	<div id="wrapper">
		<div id="header">
			<h1 class="T"><center><b>All Posts</b></center></h1>
			
		</div><br><br>
		<div id="lo"><%= link_to "Logout",session_logout_path ,{style:"color: #4169E1"}%></div>
		<div id="you">	<%= link_to "Post", new_post_path, {style: "color: #4169E1"}%></div>
		<div id="my">	<%= link_to "My Post", post_index_path, {style: "color: #4169E1"}%></div>
		<div id="users"><%= link_to "All Users", session_show_path,{style: "color: #4169E1"} %>
	  </div>
		  <%unless @posts.blank? %>
					<hr>
					<% @posts.each do|post| %>
					<div class="P">Post By:</div> 
					<%= find_user(post.user_id).name%>
					<div class="P">Title:</div>
					<%= post.title %><br>
					<div class="P">Description:</div>
					<%= post.description %><br>
					<%# debugger%>
					<ul type="square">
						<% @comment = post.comments %>
						<div class="P">Comments<br></div>
						<% @comment.each do|com|%>
						<li><%= com.description%></li>
						<small style="color:#4169E1">By: <%= find_user(com.user_id).name %> | <%= find_user(com.user_id).created_at%> | <%=link_to "Delete",post_comment_path(post.id, com.id), :method => :delete  %> | <%= link_to "Edit", edit_post_comment_path(post.id,com.id) if @current_user.id == com.user_id%>
						</small>
						<%end%><br>
							<%= link_to "Comment", {:controller=>"comment",:action =>"new",:post=> post.id }%>
					</ul>
					<hr>
						<%end%>
		  <%end%>
		  </div>	
	</body>
</html>


							
							



		  	
		
					
						
						
							

							
								
							  
	
	

					
						
							
		  		
		  	

app/views/user/new.html.erb
 <!DOCTYPE html>
<html>
	<head>
		<title></title>
		<link rel="stylesheet" type="text/css" href="application.css">
	</head>
<body>
<div id="wrapper">
	<div id="header">
		<h1 class="T"><center><b>New Sign Up</b></center></h1>
	</div><br><br>
		<div id="left_navigation"><br><br>
			<%= form_for @user , url:{action:"create"} do|f|%>
				<% if @user.errors.any? %>
							<h1>Error</h1>
							<ul>
								<%= @user.errors.full_messages%>
								<%end%>
							</ul>	
				<p style="Color:White"><b>
					<%= f.label  :name  %>
					<p><%= f.text_field :name %></p><br><br>
					</b>
				</p>
				<p style="color:White"><b>
					<%= f.label  :email %> 
					<p><%= f.text_field :email %></p><br><br>
					</b>
				</p>
				<p style="Color:White"><b>
					<%= f.label :password%>
					<p><%= f.password_field :password %></p><br><br>
					</b>
				</p>
					<p style="Color:White"><b>
						Confirm password
						<p><%= f.password_field :password %></p><br><br>
						</b>
				</p>
				<%= f.submit "Create", {style: "color: #4169E1"}%>
			<%end%>
		</div>
		</div>
</body>
</html>
 
			

			


		 		
		 		
			

				

app/views/user/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" type="text/css" href="application.css">
</head>
<body>

	<div id="wrapper">
		<div id="header">
			<h1 class="T"><center><b><%= @user.name %></b></center></h1>
		</div><br><br>
		<div id="lo"><%= link_to "Logout",session_logout_path ,{style:"color: #4169E1"}%></div>
		<div id="you">	<%= link_to "Post", new_post_path, {style: "color: #4169E1"}%></div>
		<div id="my">	<%= link_to "My Post", post_index_path, {style: "color: #4169E1"}%></div>
		<div id="users"><%= link_to "All Users", session_show_path,{style: "color: #4169E1"} %>
	  </div>
	  <%unless @posts.blank? %>
		  <hr>
				<% @posts.each do|post| %>
					<div class="P">Title<br></div>
					<%= post.title %><br>
					<div class="P">Description <br></div>
					<%= post.description %><br>
					<ul type="square">
						<% @comment = post.comments %>
						<div class="P">Comments<br></div>
						<% @comment.each do|com|%>
							<li><%= com.description%></li>
						<%end%>
					</ul>
				<%end%>
			<hr>
		<%end%>
	</div>
</body>
</html>